### ISSUE TITLE
APEX 5.1 does not have `apex_session.create_session`

### ISSUE THREAD

**Issue by rimblas** [insum-labs/starter-project-template#16]
https://github.com/insum-labs/starter-project-template/blob/a4a3198e8378efdf5fb1373ff78fb86501f477d1/release/_release.sql#L48

I'm not saying we need to cater to APEX 5.1, but we should probably have a note about it for the setup.

**Comment by martindsouza** [comment]
Done. Provided links to alternate solutions for older versions of APEX.
