### ISSUE TITLE
Bug in helper.sh missing ending fi on line 177

### ISSUE THREAD

**Issue by vitodcampanelli** [insum-labs/starter-project-template#29]
Missing ending `fi` in the function **reset_release**

<img width="563" alt="Screen Shot 2020-08-12 at 2 18 43 PM" src="https://user-images.githubusercontent.com/12102777/90052200-c837bf80-dca6-11ea-9bd2-0fc8e53fa937.png">

To reproduce error run from root folder:

```shell
./build/build.sh 1.0.0
```

<img width="861" alt="image" src="https://user-images.githubusercontent.com/12102777/90052331-fe753f00-dca6-11ea-8cb0-d8323dc329a7.png">

**Comment by martindsouza** [comment]
Fixed by #30
