### ISSUE TITLE
Ability to create APEX workspace and add developers (Wishlist)

### ISSUE THREAD

**Issue by vitodcampanelli** [insum-labs/starter-project-template#37]
This may not be in the scope of this project but wanted to ask anyways as I think it would save some time when starting a new project. Since we have the database credentials, is there any way to create the APEX workspace and add developer account(s) when the project is initially setup?

**Comment by martindsouza** [comment]
@vitodcampanelli as discussed I'll close this ticket as it's a bit out of scope of the focus of this project.
