### ISSUE TITLE
Reduce folders

### ISSUE THREAD

**Issue by martindsouza** [insum-labs/starter-project-template#5]
This project currently has a lot of folders in it which may lead to confusion and diversification of files unnecessarily. I proposes we remove the following folders. If specific projects need them they can be created:

- install
- release/ddl
- release/dml
- sql
- tmp

**Comment by martindsouza** [comment]
@rimblas  @vincentmorneau  thoughts on this?

**Comment by vincentmorneau** [comment]
release/ddl
release/dml

are the most important of all to me. The rest can go away.

**Comment by martindsouza** [comment]
@vincentmorneau why are they important to the "project"? I.e. if all "release specific" code is stored in things like `issue-123.sql` why separate ddl and dml? It's fine if you do this in your specific project (each one will have its own customizations) but why should we promote it by default?

**Comment by vincentmorneau** [comment]
I often use ddl for structural db changes, and dml for data inserts.

1. ddl: Alter table add column xyz
2. Package to calculate the value of xyz
3. dml: Populate column xyz with package from (2)

**Comment by martindsouza** [comment]
@vincentmorneau @rimblas Both interesting points. I'd like to emphasize providing a very "base set" as part of this project then encouraging people to expand for their project needs. Case in point @rimblas story about `ords` folder. I've had that in some projects because we needed it. I don't think we need to provide it out of the gate.

Could we settle on this:
- Remove all non-core folders (as listed in ticket description)
- Emphasize in the `readme` that people should modify and add what they want. I.e. this is a "base template" that one should build upon.

**Comment by vincentmorneau** [comment]
I'm good with this.

**Comment by martindsouza** [comment]
Done. If we can remove more we will as time goes on.
