### ISSUE TITLE
Provide template files

### ISSUE THREAD

**Issue by martindsouza** [insum-labs/starter-project-template#6]
Provide template files for packages, table creation, views, data scripts, etc. On the fence if we provide them as `.vscode` project snippets or explicit template files?

@vincentmorneau thoughts?

**Comment by vincentmorneau** [comment]
Explicit template files. Why have a vscode dependency?

**Comment by martindsouza** [comment]
@vincentmorneau fair point. I may include a place holder in the `.vscode` folder to state where to put common project snippets if desired.

**Comment by martindsouza** [comment]
Done. Some templates added for example.
